language: node_js
node_js:
  - '10'
  - '12'
cache:
  npm: false
before_install:
  - curl -L https://unpkg.com/@pnpm/self-installer | node
install:
  - pnpm install
script:
  - |
    cd /tmp
    create-tslib mylib default link
    cd /tmp/mylib
    pnpm run build
    pnpm run coverage
    pnpm run format
    pnpm run lint
    cd /tmp 
    create-tslib mymono monorepo link
    cd /tmp/mymono
    create-tslib mylib default link
    pnpm run build
    pnpm run coverage
    pnpm run format
    pnpm run lint
